version: '3'

vars:
  PYTHON_SOURCE: ./src

tasks:
  update-requirements:
    cmds:
      - pip list --format=freeze > "{{.PYTHON_SOURCE}}"/requirements.txt
    silent: false
  scan-mypy:
    cmds:
      - mypy src/app
  lint:
    cmds:
      - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  test:
    cmds:
      - pytest --cov=rna src/test
  create-database-migrations:
    dir: ./src
    cmds:
      - python manage.py db migrate
  local-flask:
    dotenv: [ '.env' ]
    cmds:
      - PYTHONPATH='.;./src' flask run
  local-flask-shell:
    dotenv: [ '.env' ]
    cmds:
      - PYTHONPATH='.;./src' python -m flask shell