version: '3'

vars:
  PYTHON_SOURCE: ./src

tasks:
  update-requirements:
    cmds:
      - pip list --format=freeze > "{{.PYTHON_SOURCE}}"/requirements.txt
    silent: false
  scan-mypy:
    cmds:
      - mypy src/app
  create-database-migrations:
    dir: ./src
    cmds:
      - python manage.py db migrate
  local-flask:
    dotenv: [ '.env' ]
    cmds:
      - PYTHONPATH='.;./src' flask run
  local-flask-shell:
    dotenv: [ '.env' ]
    cmds:
      - PYTHONPATH='.;./src' python -m flask shell