"""empty message

Revision ID: 9b9a9bf51481
Revises: cd417340ef00
Create Date: 2020-12-19 20:27:38.824289

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9b9a9bf51481'
down_revision = 'cd417340ef00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_commands', sa.Column('latest_exit_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
    CREATE OR REPLACE FUNCTION update_command_event() RETURNS trigger AS
$update_command_event$
BEGIN
    update host_commands
    set last_completed_at = new.completed_at,
        latest_result     = new.result,
        latest_exit_code  = new.exit_code
    where id = new.host_command_id;
    RETURN NEW;
END;
$update_command_event$ LANGUAGE plpgsql;
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_commands', 'latest_exit_code')
    # ### end Alembic commands ###
    op.execute("""
    CREATE OR REPLACE FUNCTION update_command_event() RETURNS trigger AS
$update_command_event$
BEGIN
    update host_commands
    set last_completed_at = new.completed_at,
        latest_result     = new.result
    where id = new.host_command_id;
    RETURN NEW;
END;
$update_command_event$ LANGUAGE plpgsql;
    """)
