"""empty message

Revision ID: d2cdc48aa448
Revises: 9b9a9bf51481
Create Date: 2020-12-19 23:25:26.125376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cdc48aa448'
down_revision = '9b9a9bf51481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_commands_events', sa.Column('guid', sa.String(length=155), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_commands_events', 'guid')
    # ### end Alembic commands ###
