name: Deploy to Amazon ECS

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason to run workflow'
        required: true
        default: 'I want it'
  workflow_run:
    workflows: [ "Test" ]
    branches: [ main ]
    types:
      - completed


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Images
        id: build-images
        env:
          TAG: ${{ github.sha }}
        run: |
          docker-compose build
          

      - name: Push RNA Web Image to Amazon ECR
        id: push-rna-web-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rna-web
          TAG: ${{ github.sha }}
        run: |
          # push it to ECR so that it can
          # be deployed to ECS.
          docker tag $ECR_REPOSITORY:$TAG $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

      - name: Push RNA Worker Image to Amazon ECR
        id: push-rna-worker-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rna-worker
          TAG: ${{ github.sha }}
        run: |
          # push it to ECR so that it can
          # be deployed to ECS.
          docker tag $ECR_REPOSITORY:$TAG $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

      - name: Push RNA Client Image to Amazon ECR
        id: push-rna-client-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rna-client
          TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker tag $ECR_REPOSITORY:$TAG $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

      - name: Push RNA Migrations Image to Amazon ECR
        id: push-rna-migrations-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rna-migrations
          TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker tag $ECR_REPOSITORY:$TAG $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

#      - name: Fill in the new image ID in the Amazon ECS task definition
#        id: task-def
#        uses: aws-actions/amazon-ecs-render-task-definition@v1
#        with:
#          task-definition: task-definition.json
#          container-name: sample-app
#          image: ${{ steps.build-image.outputs.image }}
#
#      - name: Deploy Amazon ECS task definition
#        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
#        with:
#          task-definition: ${{ steps.task-def.outputs.task-definition }}
#          service: sample-app-service
#          cluster: default
#          wait-for-service-stability: true