name: Deploy to Amazon ECS

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason to run workflow'
        required: true
        default: 'I want it'
  workflow_run:
    workflows: [ "Test" ]
    branches: [ main ]
    types:
      - completed


jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Images
        id: build-images
        env:
          TAG: ${{ github.sha }}
        run: |
          docker-compose build

      - name: Push RNA Web Image to Amazon ECR
        id: push-rna-web-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rna-web
          TAG: ${{ github.sha }}
        run: |
          # push it to ECR so that it can
          # be deployed to ECS.
          docker tag $ECR_REPOSITORY:$TAG $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

      - name: Push RNA Worker Image to Amazon ECR
        id: push-rna-worker-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rna-worker
          TAG: ${{ github.sha }}
        run: |
          # push it to ECR so that it can
          # be deployed to ECS.
          docker tag $ECR_REPOSITORY:$TAG $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

      - name: Push RNA Client Image to Amazon ECR
        id: push-rna-client-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rna-client
          TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker tag $ECR_REPOSITORY:$TAG $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

      - name: Push RNA Migrations Image to Amazon ECR
        id: push-rna-migrations-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rna-migrations
          TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker tag $ECR_REPOSITORY:$TAG $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

      - name: Download tasks definition
        run: |
          aws ecs describe-task-definition --task-definition RNA-Web --query taskDefinition > rna-web-definition.json
          aws ecs describe-task-definition --task-definition RNA-WOrker --query taskDefinition > rna-worker-definition.json
          aws ecs describe-task-definition --task-definition RNA-Migrations --query taskDefinition > rna-migrations-definition.json

      - name: Fill in RNA-Web Worker Definition
        id: task-def-rna-web
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: rna-web-definition.json
          image: ${{ steps.push-rna-web-image.outputs.image }}
          container-name: rna-web

      - name: Deploy RNA-Web Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-rna-web.outputs.task-definition }}
          service: RNA-WEB
          cluster: RNA
          wait-for-service-stability: true

      - name: Fill in RNA-Worker Worker Definition
        id: task-def-rna-worker
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: rna-worker-definition.json
          image: ${{ steps.push-rna-worker-image.outputs.image }}
          container-name: rna-worker

      - name: Deploy RNA-Worker Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-rna-worker.outputs.task-definition }}
          service: RNA-Worker
          cluster: RNA
          wait-for-service-stability: true

      - name: Fill in RNA-Migrations Definition
        id: task-def-rna-migrations
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: rna-migrations-definition.json
          image: ${{ steps.push-rna-migrations-image.outputs.image }}
          container-name: RNA-Migrations